- name: Create Release Archive
  run: |
    BIN_NAME=$(grep -m 1 '^name =' Cargo.toml | cut -d '"' -f 2)
    mkdir -p release
    cp "target/x86_64-unknown-linux-musl/release/$BIN_NAME" release/
