name: Rust Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable

      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross.git

      - name: Install Target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build with Cross
        run: cross build --release --target x86_64-unknown-linux-musl

      - name: Create Release Archive
        run: |
          mkdir -p release
          cp target/x86_64-unknown-linux-musl/release/vacation-tool release/

      - name: Upload Release Assets
        uses: actions/upload-artifact@v4
        with:
          name: vacation-tool-bin
          path: release/
